### ISSUE TITLE
Allow configuring list of teams that shouldn't be scheduled on the same day

### ISSUE THREAD

**Issue by ycombinator** [ycombinator/usta-match-scheduler#2]
For example, mixed 7.0 evening, women's 3.5 daytime, and men's 3.5 daytime teams should not be scheduled on the same day as they may share players.  Another example would be that the women's 3.5 daytime and 3.5 evening teams should not be scheduled on the same day.

The above examples could be expressed in configuration like so:

```yaml
teams:
  m35dt:
    # Men's 3.5 Daytime team details
  m35:
    # Men's 3.5 Evening team details
  w35dt:
    # Women's 3.5 Daytime team details
  w35:
    # Women's 3.5 Evening team details
  mx70:
    # Mixed 7.0 team details
isolated_teams:
  - m35dt, m35
  - w35dt, w35
  - mx70, m35dt, w3.5dt
```
